### ISSUE TITLE
Use Ubuntu or Debian as quest base image

### ISSUE THREAD

**Issue by wolf-yuan-6115** [linux-odyssey/linux-odyssey#111]
Currently, the quest base image is using Alpine, thus, some basic command is provided by busybox, not coreutils

Replacing the quest base image with Ubuntu or Debian can:
- Let students learn more basic commands, coreutils have more commands.
- Ubuntu and Debian are used on most cloud hosting providers.
- Students can learn how to manage system packages.

But the downside is:
- Ubuntu is big, especially if you installed a lot of packages.

**Comment by lancatlin** [comment]
We will consider this when designing further courses.
