### ISSUE TITLE
Error when running yarn build:quests

### ISSUE THREAD

**Issue by wuyihung** [linux-odyssey/linux-odyssey#92]
Hi, when I tried to install and run the command `yarn build:quests`. It fails with the following error. Could you please help?

`yarn run v1.22.21
$ yarn workspace server build:quests
warning package.json: No license field
$ node src/cli/build.js
(node:20519) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info: Building 7 images {"service":"backend","timestamp":"2023-12-11T03:42:59.421Z"}
info: Building image for copy {"service":"backend","timestamp":"2023-12-11T03:42:59.421Z"}
info: Building image for explore {"service":"backend","timestamp":"2023-12-11T03:42:59.421Z"}
info: Building image for helloworld {"service":"backend","timestamp":"2023-12-11T03:42:59.421Z"}
info: Building image for move {"service":"backend","timestamp":"2023-12-11T03:42:59.421Z"}
info: Building image for path {"service":"backend","timestamp":"2023-12-11T03:42:59.421Z"}
info: Building image for read {"service":"backend","timestamp":"2023-12-11T03:42:59.421Z"}
info: Building image for remove {"service":"backend","timestamp":"2023-12-11T03:42:59.421Z"}
file:///home/winston/linux-odyssey/server/src/containers/docker.js:112
        response.on('data', (data) => {
                 ^

TypeError: Cannot read properties of null (reading 'on')
    at file:///home/winston/linux-odyssey/server/src/containers/docker.js:112:18
    at /home/winston/linux-odyssey/node_modules/dockerode/lib/docker.js:309:9
    at Modem.buildPayload (/home/winston/linux-odyssey/node_modules/docker-modem/lib/modem.js:339:19)
    at ClientRequest.<anonymous> (/home/winston/linux-odyssey/node_modules/docker-modem/lib/modem.js:320:12)
    at ClientRequest.emit (node:events:531:35)
    at Socket.socketErrorListener (node:_http_client:495:9)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v21.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/winston/.nvm/versions/node/v21.2.0/bin/node
Arguments: /home/winston/.nvm/versions/node/v21.2.0/lib/node_modules/yarn/lib/cli.js build:quests
Directory: /home/winston/linux-odyssey/server
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by lancatlin** [comment]
Hi, thank you for submitting issue. What OS are you using? Can you tell me the version of Linux Odyssey, NodeJS, and docker?

**Comment by wuyihung** [comment]
Sure, thanks for starting helping figure it out. The system and tool information:
OS: Ubuntu 22.04
Linux Odyssey: the commit the git HEAD points to is 1bca61da40f21e0d30afd536faea08be13a90bdb.
Node.js: v21.2.0
Docker: 24.0.7

**Comment by lancatlin** [comment]
I believe this could be related to an issue of the Docker SDK we use. [dockerode: No progress on build image #697](https://github.com/apocas/dockerode/issues/697). But I can make a hot fix to handle the error. Thank you for finding this bug!

**Comment by lancatlin** [comment]
Because I cannot reproduce the error, please help me test if #94 fixes it.

**Comment by wuyihung** [comment]
I checked out the branch of #94 and reran ```yarn build:quests```, the error changes to the followings:
```
winston@winston-neihu:~/linux-odyssey$ yarn build:quests
yarn run v1.22.21
$ yarn workspace server build:quests
warning package.json: No license field
$ node src/cli/build.js
(node:7276) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info: Building 7 images {"service":"backend","timestamp":"2023-12-21T14:39:13.430Z"}
info: Building image for copy {"service":"backend","timestamp":"2023-12-21T14:39:13.430Z"}
info: Building image for explore {"service":"backend","timestamp":"2023-12-21T14:39:13.430Z"}
info: Building image for helloworld {"service":"backend","timestamp":"2023-12-21T14:39:13.430Z"}
info: Building image for move {"service":"backend","timestamp":"2023-12-21T14:39:13.430Z"}
info: Building image for path {"service":"backend","timestamp":"2023-12-21T14:39:13.430Z"}
info: Building image for read {"service":"backend","timestamp":"2023-12-21T14:39:13.430Z"}
info: Building image for remove {"service":"backend","timestamp":"2023-12-21T14:39:13.430Z"}
error: connect EACCES /var/run/docker.sock {"address":"/var/run/docker.sock","code":"EACCES","errno":-13,"service":"backend","stack":"Error: connect EACCES /var/run/docker.sock\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2023-12-21T14:39:13.430Z"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/winston/.nvm/versions/node/v21.2.0/bin/node
Arguments: /home/winston/.nvm/versions/node/v21.2.0/lib/node_modules/yarn/lib/cli.js build:quests
Directory: /home/winston/linux-odyssey/server
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by lancatlin** [comment]
It seems that you don't have permission for using docker. Can you run `docker ps`? You may need to use this command to add your user into the docker group if `id` command doesn't include `docker` in the output.

```
sudo usermod -aG docker $USER
```

**Comment by wuyihung** [comment]
Nice, I can successfully run yarn build:quests on main branch now.
